from abc import ABC, abstractmethod
import numpy as np

class Camera(ABC):
    @abstractmethod
    def open(self): ...
    @abstractmethod
    def capture(self) -> np.ndarray: ...
    @abstractmethod
    def close(self): ...
    @abstractmethod
    def is_connected(self) -> bool: ...
